repos:

-   repo: local
    hooks:
    -   id: black
        name: black
        entry: poetry -C pydantic_br run black --check
        language: system
        types: [python]

-   repo: local
    hooks:
    -   id: isort
        name: isort
        entry: poetry -C pydantic_br run isort --check
        language: system
        types: [python]

-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: poetry -C pydantic_br run mypy
        language: system
        types: [python]

-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: poetry -C pydantic_br run flake8
        language: system
        types: [python]