version: 2

mkdocs:
  configuration: mkdocs.yml

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

  jobs:
    post_create_environment:
      - pip install --user --requirement < poetry export --only doc --format requirements.txt

    post_install:
      - poetry install --only doc